name: Background poly

on:
  workflow_dispatch

permissions: read-all

env:
  SUMO_HOME: /usr/share/sumo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      run: |
        sudo add-apt-repository ppa:sumo/stable
        sudo apt-get update
        sudo apt-get install -y \
          osmctools osmosis \
          sumo-tools

    - name: Download OSM data
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: pipeline.yml
        github_token: ${{secrets.GITHUB_TOKEN}}
        name: porto-osm

    - name: Build
      run: |
        ls -la
        make -C background/osm

    - name: Upload background
      uses: actions/upload-artifact@v2
      with:
        name: porto-background-poly
        path: background/osm/porto.poly.xml
    
