name: Pipeline

on:
  push

env:
  SUMO_HOME: /usr/share/sumo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get commit datetime
      run: |
        echo "OSM_DATE=$(git show -s --format=%cI)" >> $GITHUB_ENV

    - name: Setup
      run: |
        sudo add-apt-repository ppa:sumo/stable
        sudo apt-get update
        sudo apt-get install -y \
          osmctools osmosis \
          sumo-tools

    - name: Get OSM data
      run: |
        make porto-unbounded.osm

    - name: Upload OSM
      uses: actions/upload-artifact@v2
      with:
        name: porto-osm
        path: porto-unbounded.osm

    - name: Build
      run: |
        make
    
    - name: Upload network
      uses: actions/upload-artifact@v2
      with:
        name: porto-sumo
        path: porto.net.xml
        
    - name: Check TAZ validity
      run: |
        ./checkTAZValidity.py porto.net.xml porto.taz.xml 
